const API_KEY = "1";

export const API_URL = `https://www.themealdb.com/api/json/v1/${API_KEY}/`;

export const COUNTRY_CODES = {
    'American': 'us',
    'British': 'gb',
    'Canadian': 'ca',
    'Chinese': 'cn',
    'Croatian': 'hr',
    'Dutch': 'de',
    'Egyptian': 'eg',
    'Filipino': 'ph',
    'French': 'fr',
    'Greek': 'gr',
    'Indian': 'in',
    'Irish': 'ir',
    'Italian': 'it',
    'Jamaican': 'jm',
    'Japanese': 'jp',
    'Kenyan': 'ke',
    'Malaysian': 'my',
    'Mexican': 'mx',
    'Moroccan': 'ma',
    'Polish': 'pl',
    'Portuguese': 'pt',
    'Russian': 'ru',
    'Spanish': 'es',
    'Thai': 'th',
    'Tunisian': 'tn',
    'Turkish': 'tr',
    'Ukrainian': 'xx',
    'Unknown': 'xx',
    'Vietnamese': 'vn',
};
